# name: Upload Website

# on:
#   workflow_dispatch:
#   push:
#     branches:
#     - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl private --follow-symlinks --delete
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: 'us-east-1'
#         SOURCE_DIR: 'website'
name: Deploy Website and Provision Infrastructure

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Run Terraform Apply
      id: terraform
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
      env:
        TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_aws_region: 'us-east-1'

  website:
    runs-on: ubuntu-latest

    needs: deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Wait for Terraform to complete
      uses: jakejarvis/wait-action@v1
      with:
        jobs: deploy

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy Website to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
        SOURCE_DIR: 'website'
